import { useClerk } from "@clerk/nextjs";
import { Button, Title } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { openSignIn } = useClerk();
  return (
    <>
      <Head>
        <title>Social Sphere 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Hello</Title>
      <Button onClick={() => openSignIn()}>Sign in</Button>
    </>
  );
};

export default Home;
