import { type NextPage } from "next";
import Head from "next/head";
import { Tabs } from "~/components/common/Tabs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Social Sphere 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs />
    </>
  );
};

export default Home;
