import { Button, Title } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Social Sphere 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title className="text-green-500">Hello</Title>
      <Button>Sign in</Button>
    </>
  );
};

export default Home;
